#+title: Hello
#+date: <2021-01-14 Thu 23:58>
#+filetags: hello

Coming to you from [[https://github.com/bastibe/org-static-blog][nearly-nine-hundred lines]] of Emacs-lisp and a [[https://sandyuraz.com/styles/org.min.css][pittance]] of
CSS. Do you really need more? [fn:1] In time I'll accumulate more bits and
pieces of customization and configuration to apply, better expressing myself
through this site. As it stands now this little veneer suffices, it's never
really about what's on the cover anyway, but how effective the cover is at
appealing to those that may appreciate the content. As long as you can make out
the shapes of these letters in the order I have lain them out and we can speak
alike, you have some chance of catching my drift.

More interesting to me, than ~family=Inconsolata~, is the set of pipes and gears
that thrum and turn making manifest those thoughts cannily caught, cast into
concrete from what was once ineffable as birdsong's last reflection on a sun
bleached birch tree. The fleeting formation neurons firing a whispering voice to
an inner ear which hands can transcribe, digits to digits. Ten to two (that
is one and zero) and back again, if this bird's song is sweet enough to echo off
the bark of your mind.

Emacs has long been my preferred editor, OS, and church. It's just a damn fine
piece of software.

#+html: <img src=" https://cdn.vox-cdn.com/thumbor/4p6C2WQTIBKbvVFdYk0q0_l3Wu0=/0x0:2995x3000/920x613/filters:focal(1852x1028:2330x1506):format(webp)/cdn.vox-cdn.com/uploads/chorus_image/image/54841361/twin_peaks_abc_archives.0.jpg">

There isn't much like it, comparisons to other editors are usually misguided
because it isn't anything like other editors. An old joke is Emacs is a good OS,
it just lacks a good text editor. A slightly younger joke is, that's true but we
can emulate VI now. Really it's a text programming environment

* Footnotes

[fn:1]Only if you need features™ like working footnotes
