#+title: Zathura from the Mountain
#+date: <2021-01-16 18:06>
#+filetags: musing

Part of my resolutions for the new year is to blog as often as possible, which
would have felt rather indulgent and narcissistic when I was older, but I'm
younger than that now. The word itself I find unattractive, the 'b' bursting
from pursed lips, the 'l' scraping past hard palate, the 'o' filling the mouth
with its round sound conjuring a glottal 'g'. It's charming though, in its
clumsiness. Originating from "web log" from when the internet was young and the
uses of the medium were less usual, more strange. Regardless of the history of
blogging it is today a useful source of technical information, as the people who
generally still have blogs are technical people. Laymen have services and
platforms with lower barrier to entry and maintenance, though this usually
entails being as the product bought and sold. Not very condusive to privacy,
security, or sanity to have quantifications of your essential nature bundled up
and sold en masse to the highest bidder aiming for your demo.

Blogging in comparison is much more wholesome so I'm not as concerned with my
potential narcissism for running one. To me at this moment keeping this blog is
a way to require something of myself which is presentable, so at least the
potential for an audience is necessary to motivate myself into keeping to that.
This comes at time when general precautionary measures are in effect so as to
avoid infection by disease, meaning contact with other people is rather scarce.
We're a social creature, humans. If you doubt this to any degree, just look to
the punitive system where solitary confinement is among the harshest punishments
that can be levied. We simply require contact, there is no two-ways about it.
The Hermit may momentarily escape the trappings of civilization in the
mountains, but the only way for his solitude to have meaning is for it to
eventually end. 
